apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-resizer
  labels:
    app: image-resizer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-resizer
  template:
    metadata:
      labels:
        app: image-resizer
    spec:
      nodeSelector:
        kubernetes.io/os: linux

      containers:
      - name: image-resizer
        image: mahendrshinde/image-resizer:latest
        resources:
          limits:
            memory: "200Mi"
            cpu: '500m'
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 25
          timeoutSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: image-resizer
spec:
  selector:
    app: image-resizer
  ports:
  - port: 8080
    targetPort: 8080
